### ISSUE TITLE
Bug in `ListResourceRecordSets` command

### ISSUE THREAD

**Issue by saschat** [memcachier/aws-route53#5] opened 2016-03-01 23:48 UTC
Setting `lrrsRecordType` to `Just CNAME` in the `ListResourceRecordSets` command results in an error: `XmlException {xmlErrorMessage = "Missing Error Message"}`

**Comment by saschat** [comment] 2016-09-28 15:50
This seems to be by design (Type can only be set if Name is set as well): http://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html

**Comment by dterei** [comment] 2017-02-12 05:37
@saschat given this is by design, can we close this issue then?

**Closed as completed** 2017-02-13 13:35 UTC
Labels: bug
